[package]
name = "master"
version = "0.1.0"
authors = ["Andrea Jemmett <andreajemmett@gmail.com>"]

[dependencies]
log = "0.3"
pretty_env_logger = "0.1"
zmq = "0.8"
ctrlc = { version = "3.0", features = ["termination"] }
nix = "0.9.0"
getopts = "0.2"
time = "0.1"
rand = "0.3"
inotify = "0.5"
